image:
    file: .gitpod.Dockerfile
tasks:
  - init: |
      # Install Nodejs version specified in .nvmrc
      fnm install
      fnm use
      # Install repo dependencies
      npm run setup-local
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - firsttris.vscode-jest-runner
